language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "jeorryb"
  password:
    secure: "guBTC3s/u+u9X2CgimLoo2ysqLNOZVRkiTAVUNBqzE+br3deyeoWbKnLJr5SzTcjX5vdk+n429GjvmHna+wIM5Mg+i2R0xHMl0oV9Zj0hWN7n9w9oj3/s4aWxgQ1yIrrtwrYww6k60rqAC5M1qcrC6q8u80dOuPzqARJa03Vq5s6QHajDUeKi/77t7R0D9Qmy7nXyp3OabVdKx7iCWnnzYYxDOscCSoTiXGFCZTZZCS8JMBKkqKgCTdlX2y3rxp7f6y8XvapNRuu1zZ+yroIOyKN6E3Ln4uTj8gsUyE/HOy1Zw2ng6ymT+DLSmJjQIyWRlnnWfC0ERWc5DlhjcRZ0rWF42p6wyKkNbM5JoObHLekg1dVn0BHc1AsI+SpS2PJ8vFC2QfXOVCZOKdcuUmpkhCHnWQ14v00/DdtgZTuNxK61SsZhWKOWBBcW1Z+Kh1zJUmF+0yC1CPBger6sf/tHjUVA2BRUjf40ylJhZazHkc9p3vcmReAOCHy588pcfTdd2pMlH+K8WREHKN3IgAKxHHJ+4AtUgnpPgtJYYB46PCcflLN1bQAzwLGCORVFzXv7QxuxKfmBSLO193NQh6usqGmkUn5ZecrOTDzVfM7qt/1xIcgfEH0hgF1AIGbAJhZB25aKEzR5HFSSwlTtMu6hMBiu2QbQ12Vj06A/Sf3nbs="
  on:
    tags: true
    repo: jeorryb/pyasan
    python: 3.6
