language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jeorryb
  password:
    secure: ttB60YXP1zppzX/vJC/zjAWQHa3XkJOkezUTh2PMOQawiMwiy6mzN7GDhwsegpXTHZuZfYVq71PdyIPYrewcQ+BtwFT4fgFOXDRyxKHP0NUiWwczG7uZkHTl8P+qay2f31B8VmR8TgWcRuB6LIaVPElrWb5MeG4dlpsVpLyuie11R6NB1EcsP7FYPOST1XtMX+7wj6fEg96/KeyejXNeaBeQov3qGvfSjMfgggLUWVeSXGaZb1v639QQ1/F0Q7zOkpo9Q+sI2czwfp3fQaaQhZKYVPYyRRaEQBtuOW3DWrTp2G1cXLL4icz0RNSndCSncaVhJJr3C6S/adq1yNKOI9B3c9m4ZMzlzZoOIQ/NXIV3QVOThxucuFnz5UyzeGtQe2YfCb0O+gBEDOwyxWYQVGaS01N9U7rj4PllHSqZrv8LUjcPqqp46Q2ZwEkuJwsdwv20w6526xw4yh6Iz5XXipue9fVVtSQZmzFP3C4AGVSOmSLgAvWVkxKc1HJGgXH8U01JqmTCHSLDMWJ7R9wP/BZPjkaiAgPEy+6tU/uHcL5KSRGf7ecyTNhgy7NzbE8UqhNf6V4uqbPHBTFu+iV94A+PKoF7WWEoxO/xP5sr5toxCAbh2umgXH2Wgx4hlULvd2F/rYjuqnhsFnOuVZ8/0gP6ZtYwxMx9hEWAK45WZF0=
  on:
    tags: true
    repo: jeorryb/pyasan
    python: 3.6
